export const GET_DISCOUNTS = "GET_DISCOUNTS";
export const GET_DISCOUNT = "GET_DISCOUNT";
export const CREATE_DISCOUNT = "CREATE_DISCOUNT";
export const UPDATE_DISCOUNT = "UPDATE_DISCOUNT";
export const DELETE_DISCOUNT = "DELETE_DISCOUNT";
